require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JuiceboxesController do

  # This should return the minimal set of attributes required to create a valid
  # Juicebox. As you add validations to Juicebox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JuiceboxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all juiceboxes as @juiceboxes" do
      juicebox = Juicebox.create! valid_attributes
      get :index, {}, valid_session
      assigns(:juiceboxes).should eq([juicebox])
    end
  end

  describe "GET show" do
    it "assigns the requested juicebox as @juicebox" do
      juicebox = Juicebox.create! valid_attributes
      get :show, {:id => juicebox.to_param}, valid_session
      assigns(:juicebox).should eq(juicebox)
    end
  end

  describe "GET new" do
    it "assigns a new juicebox as @juicebox" do
      get :new, {}, valid_session
      assigns(:juicebox).should be_a_new(Juicebox)
    end
  end

  describe "GET edit" do
    it "assigns the requested juicebox as @juicebox" do
      juicebox = Juicebox.create! valid_attributes
      get :edit, {:id => juicebox.to_param}, valid_session
      assigns(:juicebox).should eq(juicebox)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Juicebox" do
        expect {
          post :create, {:juicebox => valid_attributes}, valid_session
        }.to change(Juicebox, :count).by(1)
      end

      it "assigns a newly created juicebox as @juicebox" do
        post :create, {:juicebox => valid_attributes}, valid_session
        assigns(:juicebox).should be_a(Juicebox)
        assigns(:juicebox).should be_persisted
      end

      it "redirects to the created juicebox" do
        post :create, {:juicebox => valid_attributes}, valid_session
        response.should redirect_to(Juicebox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved juicebox as @juicebox" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juicebox.any_instance.stub(:save).and_return(false)
        post :create, {:juicebox => {  }}, valid_session
        assigns(:juicebox).should be_a_new(Juicebox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juicebox.any_instance.stub(:save).and_return(false)
        post :create, {:juicebox => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested juicebox" do
        juicebox = Juicebox.create! valid_attributes
        # Assuming there are no other juiceboxes in the database, this
        # specifies that the Juicebox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Juicebox.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => juicebox.to_param, :juicebox => { "these" => "params" }}, valid_session
      end

      it "assigns the requested juicebox as @juicebox" do
        juicebox = Juicebox.create! valid_attributes
        put :update, {:id => juicebox.to_param, :juicebox => valid_attributes}, valid_session
        assigns(:juicebox).should eq(juicebox)
      end

      it "redirects to the juicebox" do
        juicebox = Juicebox.create! valid_attributes
        put :update, {:id => juicebox.to_param, :juicebox => valid_attributes}, valid_session
        response.should redirect_to(juicebox)
      end
    end

    describe "with invalid params" do
      it "assigns the juicebox as @juicebox" do
        juicebox = Juicebox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juicebox.any_instance.stub(:save).and_return(false)
        put :update, {:id => juicebox.to_param, :juicebox => {  }}, valid_session
        assigns(:juicebox).should eq(juicebox)
      end

      it "re-renders the 'edit' template" do
        juicebox = Juicebox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juicebox.any_instance.stub(:save).and_return(false)
        put :update, {:id => juicebox.to_param, :juicebox => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested juicebox" do
      juicebox = Juicebox.create! valid_attributes
      expect {
        delete :destroy, {:id => juicebox.to_param}, valid_session
      }.to change(Juicebox, :count).by(-1)
    end

    it "redirects to the juiceboxes list" do
      juicebox = Juicebox.create! valid_attributes
      delete :destroy, {:id => juicebox.to_param}, valid_session
      response.should redirect_to(juiceboxes_url)
    end
  end

end
